<?php

namespace App\CouponApp\Modules\Categories\Web\Models;

use App\CouponApp\BaseCode\Models\BaseModel;
use Spatie\QueryBuilder\AllowedFilter;
use TCG\Voyager\Facades\Voyager;
use TCG\Voyager\Traits\Translatable;

class Category extends BaseModel
{
    use Translatable;

    protected $translatable = ['slug', 'name'];

    protected $table = 'categories';

    protected $fillable = [
        'parent_id',
        'order',
        'name',
        'slug',
        'logo',
    ];

    function getDefaultListingFields()
    {
        return ['id','name'];
    }
    public function parent()
    {
        return $this->belongsTo(Category::class, 'parent_id');
    }

    public function children()
    {
        return $this->hasMany(Category::class, 'parent_id');
    }
    public function getAllowedFilters()
    {
        return [
            AllowedFilter::exact('parent_id'),
            AllowedFilter::exact('order'),
            AllowedFilter::exact('name'),
            AllowedFilter::exact('slug'),
        ];
    }

    public function getAllowedIncludes()
    {
        return ['translations','parent', 'children']; // TODO: Change the autogenerated stub
    }
}
