<?php

namespace App\CouponApp\Modules\Pages\Web\Models;

use App\CouponApp\BaseCode\Models\BaseModel;

class Page extends BaseModel
{
    public function getAllowedIncludes()
    {
        return ['translations']; // TODO: Change the autogenerated stub
    }
}
