<?php

namespace App\CouponApp\Modules\Pages\Web\Models;

use App\CouponApp\BaseCode\Models\BaseModel;
use App\CouponApp\BaseCode\Translatable;

class Page extends BaseModel
{
    use Translatable;
    protected $appends = ['formatted_translations'];
    public function getAllowedIncludes()
    {
        return ['translations']; // TODO: Change the autogenerated stub
    }
}
