<?php

namespace App\CouponApp\Modules\FaqCategories\Web\Models;

use App\CouponApp\BaseCode\Models\BaseModel;
use App\CouponApp\Modules\Faqs\Web\Models\Faq;
use Illuminate\Database\Eloquent\Relations\HasMany;
use TCG\Voyager\Traits\Translatable;

class FaqCategory extends BaseModel
{

    use Translatable;


    protected $translatable = ['name'];

    protected $fillable = [
        'name', 'is_active'
    ];

    public function faqs(): HasMany
    {
        return $this->hasMany(Faq::class);
    }


    // Hidden fields for array representation
    protected $hidden = [
        // Add fields you want to hide
    ];

    // Cast attributes to specific types
    protected $casts = [
        // Add your casts here
    ];

    public function getAllowedIncludes()
    {
        return ['faqs'];// TODO: Change the autogenerated stub
    }
}
